services:
  mongo:
    image: mongo
    mem_limit: 1g
    container_name: avocet-mongodb
    restart: always
    ports:
      - "27017:27017"
    tmpfs:
      - /data/db
    # volumes:
    #   - ${HOME}/dev/data/mongodb:/data/db
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    env_file: "mongo.env"
    healthcheck:
      test: mongosh
      interval: 2s
      timeout: 60s
      start_period: 4s